config/routes.rb
Rails.application.routes.draw do

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  ActiveAdmin.routes(self)

  root :to => "articles#home"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in"  => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :users do
   resources :profiles 
  end
  resources :sessions

  match "/auth/:provider/callback", to: "sessions#create", via: ['get', 'post']
  get "/signout" => "sessions#destroy", :as => :signout

  get "profile_user"  => "profiles#edit", :as => "profile_user"

  resources :articles do
    resources :comments
  end

  resources :ratings, only: :update

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :title, :text, :images, :users_id

  validates :title, length: { minimum: 5 }, presence: true
  validates :text, length: {minimum: 20}, presence: true

  mount_uploader :images, ImagesUploader
  validate :image_size_validation

  belongs_to :user
  has_many :ratings
  has_many :comments

  def image_size_validation
    ::Rails.logger.info "Image should be less than 2MB"
    errors.add :images, "Image should be less than 2MB" if images.size > 2.megabytes
  end

  def average_rating
     ratings.average(:score)
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :commenter, :body

  belongs_to :article
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :phone, 
                  :avatar, 
                  :mobile_phone, 
                  :address, 
                  :status, 
                  :city, 
                  :country, 
                  :company, :blog, :extras, :user_id


  mount_uploader :avatar, AvatarUploader

  belongs_to :user
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  attr_accessible :article_id, :user_id, :score

  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  attr_accessible :email, :password, :password_confirmation
  attr_accessor :password

  before_save :encrypt_password

  has_one :profile
  has_many :ratings
  has_many :articles, dependent: :delete_all, validate: :false

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_confirmation_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth["uid"]
      user.provider = auth["provider"]
      user.email =  auth["info"]["email"] ? auth["info"]["email"] : auth["uid"]
      user.name = auth["info"]["name"]
      user.password = auth["provider"]
      user.views = 0
    end
  end

  def encrypt_password 
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id]) 
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def home
    @articles = Article.all.page params[:page]
  end

  def new
    @user = current_user
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|

      if @article.save
        format.html  { redirect_to(@article,
                      :notice => 'Post was successfully created.') }

        format.json  { render :json => @article,
                      :status => :created, :location => @article }
      else
        format.html  { redirect_to(@article,
                       :notice => @article.errors.messages.values.each { |attr, message| }
                                  ) }

        format.json  { render :json => @article.errors,
                      :status => :unprocessable_entity }
      end
    end
  
  end

  def index
    @articles = Article.where(users_id: current_user[:id]).page params[:page]
    respond_to do |format|
      format.html 
      format.json
    end
  end

 # GET /articles/1/edit
  def edit
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @article = Article.find(params[:id])
    @user = User.find(@article.users_id)

    if current_user
      @rating = Rating.where(article_id: @article.id, user_id: current_user.id).first
      unless @rating 
      @rating = Rating.create(article_id: @article.id, user_id: current_user.id, score: 0)
      end
    end

  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    respond_to do |format|
      format.html { redirect_to(@article, 
                    :notice => 'Post was successfully removed.') }
      format.json { head :no_content }
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :images, :users_id)
  end 

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment])
    redirect_to article_path(@article)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
    def create
      @user = current_user
      @profile = @user.build_profile(profile_params)
      @profile.save

      redirect_to root_path
    end

    def update
      @user = current_user
      @profile = @user.profile.update_attributes(profile_params)

      redirect_to root_path

    end

    def profile_params
      params.require(:profile).permit(:phone, :mobile_phone, :address, :city, :country, :blog, :avatar, :extras)
    end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

  def update
    @rating = Rating.find(params[:id])
    @article = @rating.article
    if @rating.update_attributes(score: params[:score])
      respond_to do |format|
        format.js
      end
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  auth = request.env["omniauth.auth"]
  if auth
    if(User.find_by_provider_and_uid(auth['provider'], auth['uid']))
      user = User.find_by_provider_and_uid(auth['provider'], auth['uid'])
      user.views = user.views + 1
      user.save
    else
      user = User.create_with_omniauth(auth)
    end
  else
    user = User.authenticate(params[:email], params[:password])
  end

    if user
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end

end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def index
 end

 def new
   @user = User.new
 end

 def show
   @user = current_user
   if @user.profile.nil?
     @profile = current_user.build_profile
   else
     @profile = @user.profile

   end
 end

 def create 
   @user = User.new(params[:user])
   if @user.save
     redirect_to root_url, :notice => "Signed up!"
   else
     render "new"
   end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_navigation.html.erb
<!-- Fixed navbar -->
 <nav class="navbar navbar-inverse navbar-fixed-top">
   <div class="container">

  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Nice Blog",  root_path, class: "navbar-brand" %>
  </div>

  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <% if current_user %>
        <li>
          <a href="#" id="profile" data-toggle="dropdown" aria-expanded="true">
            Logged in as <%= current_user.name ? current_user.name : current_user.email %>.
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="profile">
            <li><%= link_to "Profile" , current_user %></li>
          </ul>
        </li>
        <li>
          <a type="button" id="articles" data-toggle="dropdown" aria-expanded="true">
            Articles <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu" aria-labelledby="articles">
            <li role="presentation"><%= link_to "Add New Article", '/articles/new' %></li>
            <li role="presentation"><%= link_to "Show Articles", '/articles' %></li>
          </ul>
        </li>
        <li><%= link_to "Log out", log_out_path %></li>
      <% else %>
        <li>
          <%= 
          button_tag "Sign Up", 
            :class => 'btn sign_up btn-link',
            :type => 'button', 
            :data => {:toggle => 'modal',:target => '#sign_up'} 
          %></li>
        <li><%= link_to "log in", log_in_path, :class => 'btn-link' %></li>
        <li><%= link_to "Sign in with Twitter", "/auth/twitter" %></li>
        <li><%= link_to "Sign in with Github", "/auth/github" %></li>
      <% end %>
      </ul>
   </div>
  </div>
 </nav>

app/views/articles/_form.html.erb
<div class="col-lg-10">
<%= form_for(@article, :html => {:class => 'form-horizontal'}) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :text, :class => 'col-lg-2' %>
    <div class="col-lg-10">
      <%= f.bootsy_area :text, :class => 'form-control', :rows => 12 %>
    </div>
  </div>
  <div class="actions col-lg-offset-2">
    <%= f.submit 'Update Article', :class => 'btn btn-primary' %>
  </div>
<% end %>
</div>  

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/home.html.erb
 
<% @articles.each do |article| %>
  <div class="col-lg-12">
    <div class="col-lg-3">
      <%= image_tag article.images, :class => 'col-lg-12' %>
    </div>
    <div class="col-lg-9">
      <h2><%= link_to article.title, article %></h2>
      <p><%= article.text.split('.', 2)[0].html_safe %></p>
      <p><%= article.user %></p>
     </div>
  </div>
<% end %>
<%= paginate @articles %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.text %></td>

        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>
<%= paginate @articles %>

app/views/articles/new.html.erb
<div class="col-lg-10">
<div class="row">
  <h1 class="col-lg-6 col-lg-offset-2">Add New Post</h1>
</div>


<%= form_for :article, url: articles_path, :html => { :class => 'form-horizontal' } do |f| %>

  <%= f.hidden_field :users_id, :value => @user.id %>
  <div class="form-group">
    <%= f.label :title, :class => 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-lg-10 col-lg-offset-2">
      <%= f.file_field :images %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label "Body", :class => 'col-lg-2 control-label' %>
    <div class="col-lg-10">
      <%= f.bootsy_area :text, :class => 'form-control', :rows => 1, :rows => 12 %>
    </div>
  </div>


  <div class="col-lg-10 col-lg-offset-2">
    <div class="form-group">
      <%= f.submit "Save Post", :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>
</div>

app/views/articles/show.html.erb
<h2>
    <%= @article.title %>
</h2>

<% if current_user %>
  <script>
    <%= render template: "ratings/update.js" %>
  </script>
  <p>Average rating</p>
  <div id="star"></div>
  <p>Your rating</p>
  <div id="user_star"></div>
<% end %>

<p>
   <%= @article.text.html_safe %>
</p>
<div class="row">
<div class="col-lg-4">
  <div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Author</h3>
  </div>
  <div class="panel-body">
    <% if @user.name.blank? %>
      <%= @user.email %>
    <% else %>
      <%= @user.name %>
    <% end %>
  </div>
  </div>
</div>
</div>


<div class="row">
  <h2>Comments</h2>
<% @article.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= comment.commenter %>
  </p>
 
  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>
<% end %>
 
<div class="col-lg-6">
  <h2>Add a comment:</h2>
  <%= form_for([@article, @article.comments.build], :html => {:class => 'form-horizontal'}) do |f| %>
  <div class="form-group">
    <%= f.label :commenter, :class => 'col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :commenter, :class => 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body, :class => 'col-lg-2' %>
    <div class="col-lg-10"> 
      <%= f.text_area :body, :class => 'form-control' %>
    </div>
  </div>
  <div class="actions col-lg-offset-2">
    <%= f.submit 'Add Comment', :class => 'btn btn-primary' %>
  </div>
<% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Test for Altoros :: <%= Time.now.strftime '%m-%d-%y' %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body role="document">
  <%= render 'navigation' %>

  <div class="container theme-showcase" role="main">
  <!-- Main jumbotron for a primary marketing message or call to action -->
  <div class="jumbotron">
    <h1>Theme example</h1>
    <p>This is a template showcasing the optional theme stylesheet included in Bootstrap. Use it as a starting point to create something more unique by building on or modifying it.</p>
  </div>

    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, :id => "flash_#{name}", :class => "alert alert-success", :role => "alert" %>      
    <% end %>

    <%= yield %>
  </div>
  <% if !current_user %>
    <%= render 'new' %>
  <% end %>
</body>
</html>

app/views/ratings/update.js.erb
ready = function() {
  $('#star').raty({
    readOnly: true,
    score: <%= @article.average_rating %>,
    path: '/assets'
  });

  $('#user_star').raty({
    score: <%= @rating.score %>,
    path: '/assets',
    click: function(score, evt) {
      $.ajax({
        url: '/ratings/' + <%= @rating.id %>,
        type: 'PATCH',
        data: { score: score }
      }).done(function (data){});
    }
  });
};  

$(document).ready(ready)
$(document).on('page:load', ready)

app/views/users/index.html.erb
Welcome to Nice Blog

app/views/users/new.html.erb
<div class="modal fade" id="sign_up" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
      </div>
      <div class="modal-body">
          <%= form_for(@user, :html => {:class => 'form-horizontal'}) do |f| %>
              <% if @user.errors.any? %>
                <div class="error_messages">
                  <h2>Form is invalid</h2>
                  <ul>
                    <% for message in @user.errors.full_messages %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="form-group">
              <%= f.label :email, for: 'inputEmail', class: 'col-lg-3 control-label' %>
                <div class="col-lg-9">
                  <%= f.text_field :email, id: 'inputEmail', class: 'form-control' %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :password, for: 'inputPassword', class: 'col-lg-3 control-label' %>
                <div class="col-lg-9">
                  <%= f.password_field :password, id: 'inputPassword', class: 'form-control'  %>
                </div>
              </div>
              <div class="form-group">
                <%= f.label :password_confirmation, for: 'inputPasswordConfirmation', class: 'col-lg-3 control-label' %>
                <div class="col-lg-9">
                  <%= f.password_field :password_confirmation, id: 'inputPasswordConfirmation', class: 'form-control' %>
                </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <%= f.submit 'Add User', class: 'btn btn-primary' %>
              </div>
            <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <div class="row">
  <div class="col-lg-6">
      <label class="col-lg-2"><strong>Email:</strong></label>
      <div class="col-lg-10">
        <%= @user.email %>
      </div> 

     <% if !@user.provider.blank? %>
       <label class="col-lg-2"><strong>Provider:</strong></label>
       <div class="col-lg-10">
        [<%= @user.provider %>]
       </div>
       <% end %>
    </div>
  </div>

  <div class="col-lg-6">
  <fieldset>
  <legend>Profile</legend>
  <%= form_for [@user, @profile] , :html => {:multipart => true, :class => 'form-horizontal'} do |p| %>

    <div class="form-group">
      <%= p.label :phone, :class => 'col-lg-3' %>
      <div class="col-lg-9">
        <%= p.text_field :phone, :class => 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= p.label :mobile_phone, :class => 'col-lg-3' %>
      <div class="col-lg-9">
        <%= p.text_field :mobile_phone, :class => 'form-control'  %>
      </div>
    </div>
    
    <div class="form-group">
      <%= p.label :address, :class => 'col-lg-3' %>
      <div class="col-lg-9">
        <%= p.text_field :address, :class => 'form-control'  %>
      </div>  
    </div>

    <div class="form-group">
      <%= p.label :city, :class => 'col-lg-3' %>
      <div class="col-lg-9">
      <%= p.text_field :city, :class => 'form-control'  %>
      </div>
    </div>
    <div class="form-group">
      <%= p.label :country, :class => 'col-lg-3' %>
      <div class="col-lg-9">
        <%= p.text_field :country, :class => 'form-control'  %>
      </div>
    </div>
    <div class="form-group">
      <%= p.label :blog, :class => 'col-lg-3' %>
      <div class="col-lg-9">
        <%= p.text_field :blog, :class => 'form-control'  %>
      </div>
    </div>
    
    <div class="bootstrap-filestyle form-group">
        <%= p.label :avatar, :class => 'col-lg-3' %>
      <div class="col-lg-9">
        <%= p.file_field :avatar, :class => 'filestyle'  %> 
      </div>
    </div>
    <div class="form-group">
      <%= p.label :extras, :class => 'col-lg-3' %>
      <div class="col-lg-9">
        <%= p.text_field :extras, :class => 'form-control'  %>
      </div>
    </div>
  <div class="actions">
    <%= p.submit :class => 'btn' %>
  </div>
  <% end %>    
  </fieldset>
  </div>  
  <% if !@profile.avatar.blank? %> 
  <div class="col-lg-6">
    <fieldset>
      <legend>Avatar</legend>
      <%= image_tag @profile.avatar, :class => 'img-rounded img-responsive col-lg-8' %>
    </fieldset>
  </div>
<% end %>